################################################
#   AdoptOpenJDK - Ansible JCK Playbook for:   #
# ---- Ubuntu 16 on x86 (only one tested) ---- #
################################################

- hosts: ubuntu
  remote_user: root
  become: yes
  tasks:
  - block:
    - name: Load AdoptOpenJDKs variable file
      include_vars: adoptopenjdk_variables.yml
    - name: OS update -- apt-get upgrade
      apt: upgrade=safe update_cache=yes
      tags: patch_update
    - name: Install JCK prerequisistes
      apt: pkg={{ item }} state=latest
      with_items:
      - ant
      - ftpd
      - gcc
      - krb5-kdc
      - krb5-admin-server
      - pwgen
      - tomcat8
      - unzip
      - xvfb
    - name: Create Jenkins user
      action: user name="{{ Jenkins_Username }}" state=present
      ignore_errors: yes
      tags: jenkins_user
    - name: Set ssh key for jenkins user
      authorized_key:
        user: "{{ Jenkins_Username }}"
        state: present
        key: "{{ lookup('file', '{{ Jenkins_User_SSHKey }}') }}"
    - name: Create FTP user with password
      action: user name="{{ jckftp_Username }}" shell=/bin/false password={{ lookup('file', jckftp_Passwd) }} state=present
      ignore_errors: yes
      tags: ftp_user
    - name: Create file for FTP access
      copy:
        content: ""
        dest: "/home/{{ jckftp_Username }}/filename.txt"
        force: no
        owner: "{{ jckftp_Username }}"
        mode: 0755
    - name: Copy krb5.conf
      copy:
        src: conf/krb5.conf
        dest: /etc/krb5.conf
        owner: root
        group: root
        mode: 0644
        backup: yes
    - name: Configure kerberos server
      shell: kdb5_util create -r ADOPTOPENJDK_NET -W -s -P `pwgen -1`
      args:
        creates: /etc/krb5kdc/principal.kadm5
    - shell: "{{ item }}"
      with_items:
      - kadmin.local -q "addprinc -pw `pwgen -1` admin/admin@ADOPTOPENJDK_NET"
      - kadmin.local -q "addprinc -pw user1 user1/127.0.0.1@ADOPTOPENJDK_NET"
      - kadmin.local -q "addprinc -pw user2 user2/127.0.0.1@ADOPTOPENJDK_NET"
      - kadmin.local -q getprincs | egrep '^admin/admin@|^user1/|^user2/' > krb5.jckusers.txt; if test $(wc -l < krb5.jckusers.txt) -ne 3; then echo Wrong number of users - expected 3:; cat krb5.jckusers.txt; rm krb5.jckusers.txt; exit 1; fi
      args:
        creates: krb5.jckusers.txt
    - service:
        name: krb5-kdc
        state: started
    - service:
        name: krb5-admin-server
        state: started
    - service:
        name: tomcat8
        state: started
    - name: Start virtual X display on :1
      shell: Xvfb :1 &
      args:
        creates: /tmp/.X1-lock
      become: yes
      become_user: jenkins
